table 'Item translator'
	lineageTag: ca52b02b-77f7-47ef-bee5-bc51930c5bab

	measure 'Marketing Costs' =
			-(SUMX(
			    RELATEDTABLE('Sponsored Display Advertised Pr1'),
			    'Sponsored Display Advertised Pr1'[Spend]
			) + SUMX(
			    RELATEDTABLE('Sponsored Product Advertised Pr'),
			    'Sponsored Product Advertised Pr'[Spend]
			)// - [Marketin + branding]*[Quantity sold (type Order)]
			)
		lineageTag: 1d97463e-f5cd-42ae-9e8b-2c0a1c6b0366

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Branding costs' = DIVIDE([Total Spent],SUM(Transactions1[Quantity Sold]))
		lineageTag: 212739c3-025c-4c3e-bb45-d2c4c63876b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Marketing Costs%' = DIVIDE([Marketing Costs],[Total revenue])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f590b646-363e-48fb-ac19-a91cf662dd59

	measure 'Marketing yield' = IF([Marketing Costs]<> 0,[Total revenue]/-[Marketing Costs],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 428c5e66-b339-4ed1-af12-7eeaa9d4c0e6

	measure 'Marketing Costs - positive' = -[Marketing Costs]
		lineageTag: 55b45cd6-83fa-4d97-8c5b-5b3eb39bbb80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Marketing Costs% - positive' = -[Marketing Costs%]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9e992421-9b70-4269-9fb2-40e93bec7fb9

	measure 'Marketin + branding' = SUM('Sponsored Brands Campaign Repor'[Spend])/CALCULATE(SUM(Transactions1[Quantity Sold]),Transactions1[Transaction Type]="Order",ALL(Transactions1[Product SKU final]))
		lineageTag: 27377512-463c-4fed-b0da-b1b2f4a6ee38

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Marketing Costs (No Filters)' = ```
			
			CALCULATE(
			    -(
			        SUMX(
			            ALL('Sponsored Display Advertised Pr1'),
			            'Sponsored Display Advertised Pr1'[Spend]
			        ) + SUMX(
			            ALL('Sponsored Product Advertised Pr'),
			            'Sponsored Product Advertised Pr'[Spend]
			        )
			    ) / - [Marketin + branding] * [Quantity sold (type Order)]
			)
			
			```
		lineageTag: a8e262c0-a93a-454d-aba7-2a728da08c10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Marketing costs (No Filters) % - positive' = -DIVIDE([Marketing Costs (No Filters)],[Total revenue])
		lineageTag: 4217f5e3-3e6d-4758-861a-c60db560efff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Box length(cm)' = 25
		formatString: 0
		lineageTag: 75565363-11c9-4a4d-a6b5-edba31b9d58d

	measure 'Box width(cm)' = 25
		formatString: 0
		lineageTag: ee64b4a7-5c3c-4ce0-9d06-6920a89dc086

	measure 'Box height(cm)' = 25
		formatString: 0
		lineageTag: 02cc74d5-0088-4fae-b5da-cb595e059c67

	measure 'Box weight(kg)' = 25
		formatString: 0
		lineageTag: 1ae4d1c0-ba99-4bad-b6cc-8a4545613bb5

	measure 'Cubic m' = (MAX('Item translator'[Carton - L])/100)*(MAX('Item translator'[Carton - W])/100)*(MAX('Item translator'[Carton - H])/100)*[No cartons to be sent 60 days]
		formatString: 0.0000
		lineageTag: 1d4f730d-94d0-455e-acf3-4519f3d931f6

	measure 'No of pallets' = [Cubic m]/1.4
		lineageTag: 0685caa3-3c07-46ce-b976-5d99c7cbacca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carton info' = "Antal: "&[No cartons to be sent 60 days]&" - Mål: "&MIN('Item translator'[Carton - L])&"x"&MIN('Item translator'[Carton - W])&"x"&MIN('Item translator'[Carton - H])
		lineageTag: bb881ae1-90d5-45ef-8a48-f93b9b089929

	column 'Navision - Item'
		dataType: string
		lineageTag: abc95b7d-1a48-4378-bde8-0e8df85f15f1
		summarizeBy: none
		sourceColumn: Navision - Item

		annotation SummarizationSetBy = Automatic

	column 'Navision - Item 2'
		dataType: string
		lineageTag: 761428fc-7b4b-492d-a93a-08e6b6350a07
		summarizeBy: none
		sourceColumn: Navision - Item 2

		annotation SummarizationSetBy = Automatic

	column ASIN
		dataType: string
		lineageTag: 943b76fb-656c-486f-84a4-4f359ebdbf73
		summarizeBy: none
		sourceColumn: ASIN

		annotation SummarizationSetBy = Automatic

	column Amazon
		dataType: string
		lineageTag: 9d3def98-0c05-456b-b772-cff2e42d7d12
		summarizeBy: none
		sourceColumn: Amazon

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: 7d4ffd59-fefa-4a58-8e83-b597b182a66c
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column 'Description.1'
		dataType: string
		lineageTag: 385cb675-94ae-440d-b047-204e10541a5c
		summarizeBy: none
		sourceColumn: Description.1

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		lineageTag: 8803d980-b3ae-47ae-a740-558024e6652f
		summarizeBy: none
		sourceColumn: Colour

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 273f5af3-566f-4a01-bea9-1565e39a4823
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column 'Parent SKU'
		dataType: string
		lineageTag: 0fa224a9-3f7d-4eee-8dac-16681e182124
		summarizeBy: none
		sourceColumn: Parent SKU

		annotation SummarizationSetBy = Automatic

	column 'Parent ASIN'
		dataType: string
		lineageTag: 5f2ba3d0-e845-448e-83f7-b226e0eb6389
		summarizeBy: none
		sourceColumn: Parent ASIN

		annotation SummarizationSetBy = Automatic

	column 'Sales Units pr. master carton'
		dataType: int64
		formatString: 0
		lineageTag: f694bfb6-54a8-43ff-873f-02d8f6bb544b
		summarizeBy: sum
		sourceColumn: Sales Units pr. master carton

		annotation SummarizationSetBy = Automatic

	column 'Carton - L'
		dataType: double
		lineageTag: 986ec756-0d2f-40ea-9781-1bd26b3f5807
		summarizeBy: sum
		sourceColumn: Carton - L

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carton - W'
		dataType: double
		lineageTag: 24932e0b-04e6-4523-b336-bf3c609a0949
		summarizeBy: sum
		sourceColumn: Carton - W

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carton - H'
		dataType: double
		lineageTag: 912343ce-2552-4050-826c-e888fb6817fa
		summarizeBy: sum
		sourceColumn: Carton - H

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carton - KG'
		dataType: double
		lineageTag: d5aa18c4-5c5d-436f-b4dc-edb690bb70d8
		summarizeBy: sum
		sourceColumn: Carton - KG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Variant code'
		dataType: string
		lineageTag: 7e1504dd-05ac-4ab4-9efd-1db8af1f37f2
		summarizeBy: none
		sourceColumn: Variant code

		annotation SummarizationSetBy = Automatic

	hierarchy 'Parent SKU Hierarchy'
		lineageTag: 0b8df243-b398-4bf2-b6e1-95c1a36ae4af

		level 'Parent SKU'
			lineageTag: eabfe5df-7d6b-4849-a9b7-70c6ca7e2b68
			column: 'Parent SKU'

		level Amazon
			lineageTag: 9b1a5161-511c-4044-b1d8-aa99e29d1d7c
			column: Amazon

	hierarchy 'Parent ASIN Hierarchy'
		lineageTag: d3847bd6-d424-4a4b-bdfc-5eb1ed3470ef

		level 'Parent ASIN'
			lineageTag: 66314381-45fb-4d6a-b6d8-0bb7a4994bb8
			column: 'Parent ASIN'

		level ASIN
			lineageTag: 700f9f39-0c88-444e-b2d5-fbf66bc0c121
			column: ASIN

	partition 'Item translator' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://contrastcompany.sharepoint.com/sites/Milestone615", [ApiVersion = 15]),
				    #"Translator - Excel xlsx_https://contrastcompany sharepoint com/sites/Milestone615/Delte dokumenter/General/Amazon Power BI data source/" = Source{[Name="Translator - Excel.xlsx",#"Folder Path"="https://contrastcompany.sharepoint.com/sites/Milestone615/Delte dokumenter/General/Amazon Power BI data source/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Translator - Excel xlsx_https://contrastcompany sharepoint com/sites/Milestone615/Delte dokumenter/General/Amazon Power BI data source/"),
				    Ark1_Sheet = #"Imported Excel Workbook"{[Item="Ark1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Ark1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Navision - Item", type text}, {"Navision - Item 2", type text}, {"ASIN", type text}, {"Amazon", type text}, {"Product Type", type text}, {"Description", type text} }),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"ASIN"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Blank Rows", "Description", Splitter.SplitTextByEachDelimiter({"("}, QuoteStyle.Csv, false), {"Description.1", "Description.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Description.1", type text}, {"Description.2", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1",")","",Replacer.ReplaceText,{"Description.2"}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Replaced Value", "Description.2", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Description.2.1", "Description.2.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Description.2.1", type text}, {"Description.2.2", type text}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type2"," ","",Replacer.ReplaceText,{"Description.2.2"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1"," - ","",Replacer.ReplaceText,{"Description.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value2",{{"Description.2.1", "Colour"}, {"Description.2.2", "Size"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Parent SKU", each Text.Start([Amazon],7)),
				    #"Replaced Value3" = Table.ReplaceValue(#"Added Custom","-",null,Replacer.ReplaceValue,{"Carton - L"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","-",null,Replacer.ReplaceValue,{"Carton - W"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","-",null,Replacer.ReplaceValue,{"Carton - H"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","-",null,Replacer.ReplaceValue,{"Carton - KG"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","-",null,Replacer.ReplaceValue,{"Sales Units pr. master carton"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value7",{{"Sales Units pr. master carton", Int64.Type}, {"Carton - L", type number}, {"Carton - W", type number}, {"Carton - H", type number}, {"Carton - KG", type number}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Changed Type3", "Text After Delimiter", each Text.AfterDelimiter([#"Navision - Item 2"], "-", 1), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text After Delimiter",{{"Text After Delimiter", "Variant code"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

