table 'Amazon aug23 - items'
	lineageTag: 1b714905-c96c-4d16-883d-f51c5e51c142

	measure Measure
		lineageTag: 5efa6cff-05d0-4ee3-b413-6643d1cd5420

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column SKU
		dataType: string
		lineageTag: c5cbbf1d-774f-492c-b09c-f2e041ca3217
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		lineageTag: 2515cac2-1cdf-44ce-bd31-794578fe80db
		summarizeBy: none
		sourceColumn: Colour

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 1dce898b-3784-4e6b-b436-896de936ec91
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column 'Parent item'
		dataType: string
		lineageTag: 16b98c76-1f35-4f83-b9b4-1fdd81031273
		summarizeBy: none
		sourceColumn: Parent item

		annotation SummarizationSetBy = Automatic

	partition 'Amazon aug23 - items' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://contrastcompany.sharepoint.com/sites/Milestone615", [ApiVersion = 15]),
				    #"Amazon aug23 - items xlsx_https://contrastcompany sharepoint com/sites/Milestone615/Delte dokumenter/General/Amazon Power BI data source/" = Source{[Name="Amazon aug23 - items.xlsx",#"Folder Path"="https://contrastcompany.sharepoint.com/sites/Milestone615/Delte dokumenter/General/Amazon Power BI data source/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Amazon aug23 - items xlsx_https://contrastcompany sharepoint com/sites/Milestone615/Delte dokumenter/General/Amazon Power BI data source/"),
				    #"Amazon items_Sheet" = #"Imported Excel Workbook"{[Item="Amazon items",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Amazon items_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Rækkemærkater", type text}, {"Sum af Umsätze", type number}, {"Farve", type text}, {"Størrelse", type text}, {"Vare", type text}, {"Column6", type text}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type text}, {"Column14", type text}, {"Column15", type any}, {"Column16", type any}, {"Column17", type text}, {"Column18", type number}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Blank Rows", each ([Rækkemærkater] <> "(tom)" and [Rækkemærkater] <> "Hovedtotal")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"Sum af Umsätze"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Farve", "Colour"}, {"Størrelse", "Size"}, {"Vare", "Parent item"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"Column6"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"Rækkemærkater", "SKU"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns1", each not Text.StartsWith([SKU], "B")),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows1",{{"SKU", Order.Ascending}}),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"SKU"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

